name: deploy
on:
  push:
    branches:
      - master


# 一个workflow由执行的一项或多项job
jobs:
    # 一个job任务，任务名为build
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    # steps是每个Job的运行步骤，可以包含一个或多个步骤
    steps:
      # action命令，切换分支获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master
      # action命令，安装Node10
      - name: use Node.js 10
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      # action命令，install && build
      - name: npm install and build
        # 运行的命令或者 action
        run: |
          npm install
          npm run build
