name: deploy
on:
  push:
    branches:
      - master


# 一个workflow由执行的一项或多项job
jobs:
    # 一个job任务，任务名为build
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    # steps是每个Job的运行步骤，可以包含一个或多个步骤
    steps:
      # action命令，切换分支获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master
      # action命令，安装Node10
      - name: use Node.js 10
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      # action命令，install && build
      - name: npm install and build
        # 运行的命令或者 action
        run: |
          npm install
          npm run build
      # 利用action把build好的文件上传到服务器/var/www/react-app路径下,需要确认此目录已在服务端创建
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'ubuntu'   #ssh user name
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './build/*'  # 对应我们项目build的文件夹路径
          remote_path: '/var/www/html/sudoku'
